declare const sap: any;

export interface ExecuteRequestResult {
  status: number;
  headers: Record<string, string>;
  body: unknown;
}

// Global reference mapping for generating ABAP variable names
function sanitizeAbapName(name: string): string {
  let sanitized = name.replace(/[^a-zA-Z0-9_]/g, "_").toUpperCase();
  if (sanitized.length > 30) {
    sanitized = sanitized.slice(0, 30);
  }
  // Ensure it doesn't start with a number
  if (/^[0-9]/.test(sanitized)) {
    sanitized = "V_" + sanitized;
  }
  return sanitized;
}

// Convert JSON object structure to ABAP structures recursively
function jsonToAbapTypes(obj: unknown, typeName: string, generatedTypes: string[]): string {
  if (obj === null || obj === undefined) {
    return `${sanitizeAbapName(typeName)} TYPE string`;
  }

  if (Array.isArray(obj)) {
    if (obj.length === 0) {
      return `${sanitizeAbapName(typeName)} TYPE string_table`;
    }
    const sampleItem = obj[0];
    if (typeof sampleItem === "object" && sampleItem !== null) {
      const elementTypeName = `TY_${sanitizeAbapName(typeName)}_ITEM`;
      const structDef = jsonToAbapTypes(sampleItem, elementTypeName, generatedTypes);
      generatedTypes.push(structDef);
      return `${sanitizeAbapName(typeName)} TYPE STANDARD TABLE OF ${elementTypeName} WITH DEFAULT KEY`;
    } else {
      const typeStr = typeof sampleItem === "number" ? "INT4" : typeof sampleItem === "boolean" ? "ABAP_BOOL" : "STRING";
      return `${sanitizeAbapName(typeName)} TYPE STANDARD TABLE OF ${typeStr} WITH DEFAULT KEY`;
    }
  }

  if (typeof obj === "object" && obj !== null) {
    const lines: string[] = [];
    lines.push(`TYPES: BEGIN OF ${sanitizeAbapName(typeName)},`);
    
    Object.entries(obj).forEach(([key, val]) => {
      const sanitizedKey = sanitizeAbapName(key);
      if (typeof val === "object" && val !== null) {
        const nestedTypeName = `TY_${sanitizeAbapName(typeName)}_${sanitizedKey}`;
        const fieldDef = jsonToAbapTypes(val, nestedTypeName, generatedTypes);
        // If it returns a full declaration, it was parsed nested, add it to generated types
        if (fieldDef.startsWith("TYPES: BEGIN OF")) {
          generatedTypes.push(fieldDef);
          if (Array.isArray(val)) {
            lines.push(`         ${sanitizedKey} TYPE STANDARD TABLE OF ${nestedTypeName}_ITEM WITH DEFAULT KEY,`);
          } else {
            lines.push(`         ${sanitizedKey} TYPE ${nestedTypeName},`);
          }
        } else {
          // It's a table/nested definition returned directly
          lines.push(`         ${sanitizedKey} TYPE ${nestedTypeName},`);
        }
      } else {
        let typeStr = "STRING";
        if (typeof val === "number") {
          typeStr = Number.isInteger(val) ? "INT4" : "DECFLOAT34";
        } else if (typeof val === "boolean") {
          typeStr = "ABAP_BOOL";
        }
        lines.push(`         ${sanitizedKey} TYPE ${typeStr},`);
      }
    });

    lines.push(`       END OF ${sanitizeAbapName(typeName)}.`);
    return lines.join("\n");
  }

  return "";
}

// Primary JSON to ABAP Parser logic
export function generateAbapCode(jsonStr: string): string {
  try {
    const parsed = JSON.parse(jsonStr);
    const generatedTypes: string[] = [];
    const rootDef = jsonToAbapTypes(parsed, "TY_ROOT", generatedTypes);
    
    const allTypes = [...generatedTypes, rootDef].join("\n\n");
    
    return `*----------------------------------------------------------------------*
* ABAP Type Declarations & Parser Code
* Generated by SAPMock Relay Console
*----------------------------------------------------------------------*

${allTypes}

DATA: lv_json_payload TYPE string,
      ls_parsed_data  TYPE ty_root,
      lo_error        TYPE REF TO cx_root.

lv_json_payload = '${jsonStr.replace(/'/g, "''").replace(/\n/g, "' && \n'").slice(0, 1000)}${jsonStr.length > 1000 ? "... [truncated]" : ""}'.

TRY.
    " Deserialize JSON payload using standard SAP utility
    /ui2/cl_json=>deserialize(
      EXPORTING
        json             = lv_json_payload
        assoc_to_camel_case = abap_true
        pretty_name      = /ui2/cl_json=>pretty_name-camel_case
      CHANGING
        data             = ls_parsed_data
    ).
    
    " ls_parsed_data is now populated and ready for business logic
  CATCH cx_root INTO lo_error.
    " Handle parsing errors here
ENDTRY.`;
  } catch (error) {
    return `* Error parsing JSON: ${(error as Error).message}`;
  }
}

// Generate SnapLogic expression block based on target contract
export function generateSnapLogicMappings(contract: any): string {
  if (!contract) return "/* Please select a contract specification */";
  const schema = contract.responseSchema;
  const properties = schema?.properties || {};
  const mappings: Record<string, string> = {};

  Object.keys(properties).forEach((key) => {
    // Map standard camelCase REST keys to standard SAP uppercase BAPI structures
    const bapiField = sanitizeAbapName(key);
    mappings[bapiField] = `$${key}`;
  });

  return JSON.stringify(mappings, null, 2);
}

// Generate Fiori Launchpad target mapping export
export function generateFioriLaunchpadConfig(tileState: {
  title: string;
  subtitle: string;
  semanticObject: string;
  action: string;
  tileType: string;
  icon: string;
  url: string;
}): string {
  return JSON.stringify(
    {
      "sap.app": {
        "id": `sap.mock.relay.${tileState.semanticObject.toLowerCase()}.${tileState.action.toLowerCase()}`,
        "type": "application",
        "title": tileState.title,
        "description": tileState.subtitle
      },
      "sap.ui": {
        "technology": "UI5",
        "deviceTypes": {
          "desktop": true,
          "tablet": true,
          "phone": true
        }
      },
      "sap.platform.abap": {
        "uri": tileState.url
      },
      "launchpad": {
        "tileType": tileState.tileType,
        "title": tileState.title,
        "subtitle": tileState.subtitle,
        "icon": tileState.icon,
        "navigation": {
          "semanticObject": tileState.semanticObject,
          "action": tileState.action,
          "parameters": {}
        }
      }
    },
    null,
    2
  );
}

// Create the JSON to ABAP Converter Tab
export function createJsonToAbapTab(controls: any): any {
  const { VBox, HBox, Label, CodeEditor, Button, Card, CardHeader } = controls;

  const inputEditor = new CodeEditor({
    width: "100%",
    height: "280px",
    type: "json",
    value: `{
  "notificationId": 10000042,
  "equipmentNumber": "EQ-998877",
  "priorityCode": "H",
  "breakdown": true,
  "defectDetails": {
    "defectCode": "MECH_FAIL",
    "defectText": "Motor main shaft alignment deviation detected",
    "loggedAt": "2026-06-01T15:52:00Z"
  },
  "items": [
    { "itemPos": 10, "partNumber": "PRT-098", "quantity": 1 },
    { "itemPos": 20, "partNumber": "PRT-112", "quantity": 4 }
  ]
}`
  });

  const outputEditor = new CodeEditor({
    width: "100%",
    height: "360px",
    type: "javascript",
    editable: false,
    value: ""
  });

  const generateBtn = new Button({
    text: "Convert to ABAP Types & Parser",
    icon: "sap-icon://syntax",
    type: "Emphasized",
    press: () => {
      const json = inputEditor.getValue();
      const abap = generateAbapCode(json);
      outputEditor.setValue(abap);
    }
  });

  // Pre-generate on init
  setTimeout(() => {
    const json = inputEditor.getValue();
    const abap = generateAbapCode(json);
    outputEditor.setValue(abap);
  }, 100);

  const viewContainer = new VBox({
    width: "100%",
    items: [
      new Label({ text: "Paste JSON REST Payload" }).addStyleClass("sapUiTinyMarginBottom"),
      inputEditor,
      new HBox({
        justifyContent: "Center",
        items: [generateBtn]
      }).addStyleClass("sapUiSmallMarginTop sapUiSmallMarginBottom"),
      new Label({ text: "Generated ABAP Structure Declarations & Deserializer (/UI2/CL_JSON)" }).addStyleClass("sapUiTinyMarginBottom"),
      outputEditor
    ]
  });

  return new Card({
    header: new CardHeader({
      title: "JSON to ABAP Dictionary & Parser Generator",
      subtitle: "Map JSON payloads directly to ABAP structures for custom REST services",
      iconSrc: "sap-icon://syntax"
    }),
    content: new VBox({
      items: [viewContainer]
    }).addStyleClass("sapUiContentPadding")
  });
}

// Create the SnapLogic Mapper Tab
export function createSnapLogicTab(controls: any, data: any): any {
  const { VBox, Label, CodeEditor, Select, Item, Card, CardHeader } = controls;

  const selectContract = new Select({
    width: "100%"
  });

  data.contracts.forEach((itemVal: any) => {
    selectContract.addItem(new Item({ key: itemVal.id, text: `${itemVal.method} ${itemVal.path} (${itemVal.system})` }));
  });

  const outputEditor = new CodeEditor({
    width: "100%",
    height: "320px",
    type: "json",
    editable: false,
    value: ""
  });

  const updateMappings = () => {
    const selectedKey = selectContract.getSelectedKey();
    const contract = data.contracts.find((c: any) => c.id === selectedKey);
    const mappings = generateSnapLogicMappings(contract);
    outputEditor.setValue(mappings);
  };

  selectContract.attachChange(updateMappings);

  // Trigger initial generate
  setTimeout(updateMappings, 200);

  const viewContainer = new VBox({
    width: "100%",
    items: [
      new Label({ text: "Select Target Contract Specification" }).addStyleClass("sapUiTinyMarginBottom"),
      selectContract,
      new Label({ text: "Generated SnapLogic Mapper Snap Expression Mappings" }).addStyleClass("sapUiMediumMarginTop sapUiTinyMarginBottom"),
      outputEditor
    ]
  });

  return new Card({
    header: new CardHeader({
      title: "SnapLogic JSON-to-SAP Field Mapper",
      subtitle: "Generate property translations between Fiori REST schemas and backend BAPI inputs",
      iconSrc: "sap-icon://arrow-right"
    }),
    content: new VBox({
      items: [viewContainer]
    }).addStyleClass("sapUiContentPadding")
  });
}

// Create the Fiori Launchpad Tile Designer Tab
export function createLaunchpadTab(controls: any): any {
  const { VBox, HBox, Label, Input, Select, Item, CodeEditor, Card, CardHeader, Text } = controls;

  // Local tile preview states
  const formState = {
    title: "QM Supplier Console",
    subtitle: "Track Quality Notifications",
    semanticObject: "QMNotification",
    action: "display",
    tileType: "sap.ushell.ui.tile.StaticTile",
    icon: "sap-icon://quality",
    url: "/sap/bc/ui5_ui5/sap/zqm_supplier"
  };

  // Form controls
  const titleInput = new Input({
    value: formState.title,
    liveChange: (event: any) => {
      formState.title = event.getParameter("value");
      updateAll();
    }
  });

  const subtitleInput = new Input({
    value: formState.subtitle,
    liveChange: (event: any) => {
      formState.subtitle = event.getParameter("value");
      updateAll();
    }
  });

  const semObjInput = new Input({
    value: formState.semanticObject,
    liveChange: (event: any) => {
      formState.semanticObject = event.getParameter("value");
      updateAll();
    }
  });

  const actionInput = new Input({
    value: formState.action,
    liveChange: (event: any) => {
      formState.action = event.getParameter("value");
      updateAll();
    }
  });

  const iconInput = new Input({
    value: formState.icon,
    liveChange: (event: any) => {
      formState.icon = event.getParameter("value");
      updateAll();
    }
  });

  const tileTypeSelect = new Select({
    selectedKey: formState.tileType,
    change: (event: any) => {
      formState.tileType = event.getSource().getSelectedKey();
      updateAll();
    }
  });
  tileTypeSelect.addItem(new Item({ key: "sap.ushell.ui.tile.StaticTile", text: "Static App Tile" }));
  tileTypeSelect.addItem(new Item({ key: "sap.ushell.ui.tile.DynamicTile", text: "Dynamic Count Tile" }));

  // Live preview element (Mock UI5 HTML rendering)
  // We can build a custom HTML wrapper block or a clean Fiori tile mockup using standard VBox elements
  const previewTitle = new Text({ text: formState.title }).addStyleClass("sapmockTileTitle");
  const previewSubtitle = new Text({ text: formState.subtitle }).addStyleClass("sapmockTileSubtitle");
  const previewNumber = new Text({ text: "12" }).addStyleClass("sapmockTileNumber");
  
  // Set initial dynamic visibility
  previewNumber.setVisible(false);

  const previewBox = new VBox({
    width: "150px",
    height: "150px",
    items: [
      previewTitle,
      previewSubtitle,
      new VBox({
        alignItems: "End",
        justifyContent: "End",
        width: "100%",
        items: [previewNumber]
      }).addStyleClass("sapUiMediumMarginTop")
    ]
  }).addStyleClass("sapMGT"); // Styled using our generic tile CSS class!

  const configEditor = new CodeEditor({
    width: "100%",
    height: "260px",
    type: "json",
    editable: false,
    value: ""
  });

  function updateAll() {
    previewTitle.setText(formState.title);
    previewSubtitle.setText(formState.subtitle);
    if (formState.tileType === "sap.ushell.ui.tile.DynamicTile") {
      previewNumber.setVisible(true);
    } else {
      previewNumber.setVisible(false);
    }
    const config = generateFioriLaunchpadConfig(formState);
    configEditor.setValue(config);
  }

  // Initial trigger
  setTimeout(updateAll, 200);

  // Field helpers
  function formField(labelText: string, control: any) {
    return new VBox({
      width: "100%",
      items: [
        new Label({ text: labelText }),
        control
      ]
    }).addStyleClass("sapmockField");
  }

  const formLayout = new HBox({
    width: "100%",
    items: [
      formField("Tile Title", titleInput),
      formField("Tile Subtitle", subtitleInput),
      formField("Semantic Object", semObjInput),
      formField("Action", actionInput),
      formField("Launchpad Icon", iconInput),
      formField("Tile Mode Type", tileTypeSelect)
    ]
  }).addStyleClass("sapmockFormGrid");

  const previewLayout = new HBox({
    width: "100%",
    alignItems: "Start",
    items: [
      new VBox({
        width: "200px",
        items: [
          new Label({ text: "Launchpad Tile Preview" }).addStyleClass("sapUiTinyMarginBottom"),
          previewBox
        ]
      }),
      new VBox({
        width: "100%",
        items: [
          new Label({ text: "Target Mapping Configuration Export" }).addStyleClass("sapUiTinyMarginBottom"),
          configEditor
        ]
      }).addStyleClass("sapUiSmallMarginBegin")
    ]
  }).addStyleClass("sapUiLargeMarginTop");

  return new Card({
    header: new CardHeader({
      title: "Fiori Launchpad Designer & Tile Configuration",
      subtitle: "Model target mappings, preview tiles, and generate catalog configuration entries",
      iconSrc: "sap-icon://grid"
    }),
    content: new VBox({
      items: [formLayout, previewLayout]
    }).addStyleClass("sapUiContentPadding")
  });
}

// Create the OpenAPI Explorer Tab
export function createOpenApiExplorerTab(controls: any, data: any, selectContract: any): any {
  const { VBox, HBox, Label, Text, Button, Card, CardHeader, ObjectStatus, ObjectIdentifier, CodeEditor } = controls;

  const explorerContainer = new VBox({
    width: "100%"
  });

  data.contracts.forEach((contract: any, index: number) => {
    const methodColor = contract.method === "GET" ? "Success" : contract.method === "POST" ? "Information" : "Warning";
    
    const routeHeader = new HBox({
      alignItems: "Center",
      justifyContent: "SpaceBetween",
      width: "100%",
      items: [
        new HBox({
          alignItems: "Center",
          items: [
            new ObjectStatus({ text: contract.method, state: methodColor }).addStyleClass("sapUiTinyMarginEnd"),
            new ObjectIdentifier({ title: contract.path, text: contract.summary })
          ]
        }),
        new Button({
          text: "Load in Request Runner",
          icon: "sap-icon://process",
          type: "Emphasized",
          press: () => {
            // Load and switch
            selectContract(contract.id);
          }
        })
      ]
    }).addStyleClass("sapUiSmallMarginBottom");

    const schemaInfo = new VBox({
      width: "100%",
      items: [
        new Label({ text: "Integration Scope Target System" }).addStyleClass("sapUiTinyMarginBottom"),
        new Text({ text: `SAP Backend System ID: ${contract.system}` }).addStyleClass("sapUiSmallMarginBottom"),
        new Label({ text: "API Response Specification Schema" }).addStyleClass("sapUiTinyMarginBottom"),
        new CodeEditor({
          width: "100%",
          height: "150px",
          type: "json",
          editable: false,
          value: JSON.stringify(contract.responseSchema, null, 2)
        })
      ]
    }).addStyleClass("sapUiContentPadding");

    const contractCard = new Card({
      header: new CardHeader({
        title: `${contract.method} ${contract.path}`,
        subtitle: contract.summary,
        iconSrc: "sap-icon://document-text"
      }),
      content: new VBox({
        items: [schemaInfo, routeHeader]
      }).addStyleClass("sapUiContentPadding")
    }).addStyleClass(index > 0 ? "sapUiMediumMarginTop" : "");

    explorerContainer.addItem(contractCard);
  });

  return new Card({
    header: new CardHeader({
      title: "Interactive OpenAPI Schema Explorer",
      subtitle: "Drill down into REST integration contracts and map direct endpoints to the request simulator",
      iconSrc: "sap-icon://search"
    }),
    content: explorerContainer
  }).addStyleClass("sapUiContentPadding");
}
